language: java
before_script: cat ~/.m2/settings.xml
script: mvn -f hellojsf/pom.xml -q -X clean install
jdk:
  - oraclejdk7
# whitelist
branches:
  only:
    - master
notifications:
  email:
    - bahtiyar.erden@gmail.com
    - tayfunhalac@gmail.com
    



